# Generated by Django 4.0.3 on 2022-04-08 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.maparea'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Latitude'),
        ),
    ]
